window.CheongchunCampus = window.CheongchunCampus || {};
window.CheongchunCampus.config = window.CheongchunCampus.config || {};

window.CheongchunCampus.config.reviewForm = {
  title: "청춘캠퍼스 후기 & 애프터 신청",
  description:
    "청춘캠퍼스에 참여해주셔서 감사합니다.\n오늘의 후기와 다시 이야기해보고 싶은 분을 알려주세요.\n상호 선택이 확인된 경우에만 매칭 안내가 진행됩니다.",
  kakaoUrl: "http://pf.kakao.com/_BxcVTX",
  submitLabel: "후기 제출하기",
  successTitle: "후기 제출이 완료되었습니다.",
  successMessage:
    "상호 선택이 확인된 경우, 운영자가 순차적으로 매칭 안내를 드릴 예정입니다.\n매칭 결과는 카카오톡 채널을 통해 안내되므로, 아직 채널 채팅을 시작하지 않았다면 채널에 \"후기완료\"라고 보내주세요.\n\n참여해주셔서 감사합니다.",
  fields: [
    {
      name: "event_date",
      label: "참여한 날짜를 선택해주세요.",
      type: "select",
      required: true,
      options: [],
      dynamicOptions: "applicationPreferredDates",
      emptyLabel: "날짜를 선택해주세요.",
    },
    {
      name: "name",
      label: "이름을 입력해주세요.",
      type: "text",
      placeholder: "예: 홍길동",
      required: true,
    },
    {
      name: "phone_last4",
      label: "휴대폰 번호 뒷자리를 입력해주세요.",
      type: "text",
      placeholder: "예: 1234",
      required: true,
      inputMode: "numeric",
      maxLength: 4,
    },
    {
      name: "participant_gender",
      label: "성별을 선택해주세요.",
      type: "choice",
      required: true,
      options: ["남성", "여성", "기타 / 응답하지 않음"],
    },
    {
      name: "participant_number",
      label: "본인의 참가자 번호를 입력해주세요.",
      type: "text",
      placeholder: "예: 남자 3번 / 여자 5번",
      required: true,
    },
    {
      name: "overall_satisfaction",
      label: "전체적으로 오늘 행사는 만족스러우셨나요?",
      type: "choice",
      required: true,
      options: ["매우 만족", "만족", "보통", "아쉬움", "매우 아쉬움"],
    },
    {
      name: "conversation_time",
      label: "로테이션 대화 시간은 어땠나요?",
      type: "choice",
      required: true,
      options: ["너무 짧았다", "조금 짧았다", "적당했다", "조금 길었다", "너무 길었다"],
    },
    {
      name: "traffic_source",
      label: "청춘캠퍼스를 어디서 알게 되셨나요?",
      type: "select",
      required: true,
      options: [
        "인스타그램",
        "에브리타임",
        "카카오톡 오픈채팅",
        "지인 추천",
        "학교 커뮤니티",
        "축제/부스 현장",
        "포스터/전단지",
        "네이버 검색",
        "기타",
      ],
    },
    {
      name: "has_after_interest",
      label: "오늘 다시 이야기해보고 싶은 분이 있었나요?",
      type: "choice",
      required: true,
      options: ["있었다", "없었다"],
    },
    {
      name: "first_choice",
      label: "1순위로 다시 이야기해보고 싶은 상대 번호를 선택해주세요.",
      type: "participant-select",
      required: true,
      showWhen: { has_after_interest: "있었다" },
    },
    {
      name: "second_choice",
      label: "2순위로 다시 이야기해보고 싶은 상대 번호를 선택해주세요.",
      type: "participant-select",
      showWhen: { has_after_interest: "있었다" },
    },
    {
      name: "third_choice",
      label: "3순위로 다시 이야기해보고 싶은 상대 번호를 선택해주세요.",
      type: "participant-select",
      showWhen: { has_after_interest: "있었다" },
    },
    {
      name: "choice_reason",
      label: "선택한 이유가 있다면 간단히 적어주세요. 선택 사항입니다.",
      type: "textarea",
      placeholder: "예: 대화가 잘 통했다, 분위기가 좋았다, 더 알아가보고 싶었다 등",
      showWhen: { has_after_interest: "있었다" },
    },
    {
      name: "good_points",
      label: "오늘 가장 좋았던 점은 무엇인가요?",
      type: "textarea",
      placeholder: "예: 분위기가 편했다, 다양한 사람을 만날 수 있었다 등",
    },
    {
      name: "improvement_points",
      label: "아쉬웠던 점이나 개선되었으면 하는 점이 있나요?",
      type: "textarea",
      placeholder: "예: 대화 시간이 짧았다, 자리 이동 안내가 더 필요했다 등",
    },
    {
      name: "next_participation",
      label: "다음 행사에도 참여할 의향이 있나요?",
      type: "choice",
      options: ["있다", "고민해볼 것 같다", "없다"],
    },
    {
      name: "had_discomfort",
      label: "행사 중 불편했던 상황이 있었나요?",
      type: "choice",
      options: ["없었다", "있었다"],
    },
    {
      name: "discomfort_detail",
      label: "불편했던 내용을 간단히 적어주세요.",
      type: "textarea",
      placeholder: "운영 개선 및 안전한 행사 진행을 위해서만 확인합니다.",
      showWhen: { had_discomfort: "있었다" },
    },
    {
      name: "operation_consent",
      label: "[필수] 작성한 정보는 행사 운영 및 매칭 확인 목적으로 사용되는 것에 동의합니다.",
      type: "checkbox",
      required: true,
    },
    {
      name: "contact_share_consent",
      label: "[필수] 상호 선택이 확인된 경우 상대방에게 연락 수단이 전달될 수 있음에 동의합니다.",
      type: "checkbox",
      required: true,
    },
    {
      name: "one_way_private_confirmed",
      label: "[필수] 일방 선택 정보는 상대방에게 공개되지 않는다는 점을 확인했습니다.",
      type: "checkbox",
      required: true,
    },
  ],
};
